services:
  mongodb:
    image: l33tlamer/mongodb-without-avx
    restart: always
    volumes:
      - ./mongo_data:/data/db
  rest-api:
    image: node:lts
    command: "npm --prefix=/app start"
    restart: always
    volumes:
      - ./extensao-server:/app
  nginx:
    image: nginx:latest
    depends_on:
      - rest-api
    ports:
      - 80:80/tcp
      - 443:443/tcp
      - 443:443/udp
    volumes:
      - ./http-proxy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt/live/extensaoads2.sj.ifsc.edu.br/fullchain.pem:/etc/nginx/fullchain.pem:ro
      - /etc/letsencrypt/live/extensaoads2.sj.ifsc.edu.br/privkey.pem:/etc/nginx/privkey.pem:ro
    restart: always
