services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80/tcp
      - 443:443/tcp
      - 443:443/udp
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt/live/extensaoads2.sj.ifsc.edu.br/fullchain.pem:/etc/nginx/fullchain.pem:ro
      - /etc/letsencrypt/live/extensaoads2.sj.ifsc.edu.br/privkey.pem:/etc/nginx/privkey.pem:ro
    restart: always
