AWSTemplateFormatVersion: "2010-09-09"
Description: AWS App Runner Service for Node.js 22+ Application
Parameters:
  ServiceName:
    Description: Name of the App Runner service
    Type: String
    Default: nuvem
  RepositoryUrl:
    Description: URL of the source code repository
    Type: String
    Default: https://github.com/Extensao2/nuvem
  Branch:
    Description: Branch name to use from the repository
    Type: String
    Default: main
  BuildCommand:
    Description: Command to build your Node.js application
    Type: String
    Default: npm install
  StartCommand:
    Description: Command to start your Node.js application
    Type: String
    Default: npm start
  Port:
    Description: Port that your application listens on
    Type: Number
    Default: 3000
  GitHubConnectionArn:
    Description: ARN of the GitHub connection (must be created first in AWS Console)
    Type: String
Resources:
  AppRunnerService:
    Type: AWS::AppRunner::Service
    Properties:
      ServiceName: !Ref ServiceName
      SourceConfiguration:
        AuthenticationConfiguration:
          ConnectionArn: !Ref GitHubConnectionArn
        CodeRepository:
          RepositoryUrl: !Ref RepositoryUrl
          SourceCodeVersion:
            Type: BRANCH
            Value: !Ref Branch
          CodeConfiguration:
            ConfigurationSource: API
            CodeConfigurationValues:
              Runtime: NODEJS_22
              BuildCommand: !Ref BuildCommand
              StartCommand: !Ref StartCommand
              Port: !Ref Port
              RuntimeEnvironmentVariables:
                - Name: NODE_ENV
                  Value: production
                - Name: PORT
                  Value: !Ref Port
      InstanceConfiguration:
        Cpu: 1 vCPU
        Memory: 2 GB
      AutoScalingConfigurationArn: !Ref AppRunnerAutoScaling

  AppRunnerAutoScaling:
    Type: AWS::AppRunner::AutoScalingConfiguration
    Properties:
      AutoScalingConfigurationName: !Sub ${ServiceName}-scaling-config
      MaxConcurrency: 100
      MinSize: 1
      MaxSize: 5
Outputs:
  ServiceUrl:
    Description: URL of the App Runner service
    Value: !GetAtt AppRunnerService.ServiceUrl
  ServiceArn:
    Description: ARN of the App Runner service
    Value: !GetAtt AppRunnerService.ServiceArn
